---
- name: create users using a loop
  hosts: all
  become: yes
  vars_files:
    - vars/users_pass
  tasks:
    - name: Create users on nodes
      user:
        name: "{{ item.key }}"
        home: "/home/{{ item.key }}"
        comment: "{{ item.key }}@example.com"
        password: "{{ item.value.password | password_hash('sha512') }}"
        update_password: always
      with_dict: "{{ passwords }}"
    - name: Print passwords
      debug:
        msg:
          - "{{ item.key }}@example.com"
          - "/home/{{ item.key }}"
          - "{{ item.key }}"
          - "{{ item.value.password | password_hash('sha512') }}"
      with_dict: "{{ passwords }}"


      
